### ISSUE TITLE
OPENCV_HOME, DJINNI_HOME variable value

### ISSUE THREAD

**Issue by cuizhe1** [Fotoapparat/FaceDetector#1]
facedetector/build.gradle, there are OPENCV_HOME and DJINNI_HOME system variable.
How can I set OPENCV_HOME and DJINNI_HOME?

**Comment by dmitry-zaitsev** [comment]
Those variables need to be added to `gradle.properties` file (either local one or global one). On Mac OS it is `~/.gradle/gradle.properties`.

`DJINNI_HOME` should point to djinni home directory. 
`OPENCV_HOME` should point to OpenCV Android SDK home directory.

That's how they might look like:

```
DJINNI_HOME=/Users/Dmitry/djinni
OPENCV_HOME=/Users/Dmitry/OpenCV-android-sdk
```

With all that said, the project is technically complete, but not yet documented. I am planning to publish it on bintray in the following weeks, so that you won't have to go through hassle of building it yourself.
